name: Generate README.md File

on:
  workflow_dispatch:
  schedule:
    - cron: '27 20 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Generate README
        run: python readme_updater.py

      - name: Commit README
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout -b readme_updater
          git add .
          git commit -m "feat: Update README.md"
          git push -u https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git update
          echo "${{ secrets.README_UPDATER_TOKEN }}" | gh auth login --with-token
          gh pr create --head readme_updater --fill
          gh pr review --comment -b "Looks good to me!"
          gh pr merge -d -m